---
- name: Respaldar todas las BD MySQL/MariaDB
  hosts: all
  tasks:
    - name: Dump all
      command: mysqldump --all-databases | gzip > /backup/mysql_all_$(date +%F).sql.gz
      changed_when: true
