---
- name: Simular restauración para verificar integridad
  hosts: localhost
  ignore_unreachable: yes
  tasks:
    - name: Test
      debug:
        msg: "El script de test debe cargar el archivo en una instancia aislada."
