---
- name: Sincronizar directorios clave a NAS/S3 remoto
  hosts: all
  ignore_unreachable: yes
  vars:
    src_dir: "/var/www"
    dest_dir: "/backup/remote/"
    rsync_opts: "-avz --delete"
  tasks:
    - name: Rsync
      command: rsync {{ rsync_opts }} {{ src_dir }} {{ dest_dir }}
      changed_when: true
