---
- name: Estado de servicios Windows
  hosts: all
  vars:
    win_services: ['Spooler', 'W32Time']
  tasks:
    - name: Get service status
      win_service:
        name: "{{ item }}"
      register: win_srv
      loop: "{{ win_services }}"

    - name: Report
      debug:
        msg: |
          {% for r in win_srv.results %}
          - {{ r.item }}: {{ r.state | default('failed') }}
          {% endfor %}
