---
- name: Extraer errores críticos de Event Viewer
  hosts: all
  tasks:
    - name: Get events
      win_shell: Get-EventLog -LogName System -EntryType Error -Newest 10 | Select-Object TimeGenerated, Source, Message
      register: win_ev
      changed_when: false

    - name: Mostrar
      debug:
        var: win_ev.stdout_lines
