---
- name: Reiniciar si actualizaciones lo requieren
  hosts: all
  ignore_unreachable: yes
  tasks:
    - name: Reboot
      win_reboot:
        msg: "Reboot triggered by Ansible"
      when: reboot_required is defined and reboot_required
