---
- name: Limpiar logs de contenedores
  hosts: all
  ignore_unreachable: yes
  tasks:
    - name: Config en daemon.json (placeholder)
      debug:
        msg: "Se recomienda setear log-opts max-size y max-file en daemon.json"
