---
- name: Estado de servicios GitLab
  hosts: all
  ignore_unreachable: yes
  tasks:
    - name: Check gitlab services
      command: gitlab-ctl status
      register: gitlab_status
      changed_when: false

    - name: Report
      debug:
        msg: "{{ gitlab_status.stdout }}"
