---
- name: Optimizar bases de datos WordPress
  hosts: all
  ignore_unreachable: yes
  tasks:
    - name: Optimizar DBs
      command: wp db optimize --path={{ item }} --allow-root
      with_fileglob:
        - "/var/www/*/htdocs"
      changed_when: true
      ignore_errors: true
