---
- name: Configurar SSH seguro
  hosts: all
  ignore_unreachable: yes
  become: true
  tasks:
    - name: Deshabilitar Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        validate: 'sshd -t -f %s'
      notify: Restart SSH

    - name: Deshabilitar autenticacion por password (opcional, set to yes by default to prevent lockout)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes' # Cambiar a no en produccion asegurada

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
